import numpy as np
a = np.array(np.arange(1, 100), float)
print('ex1')
print(a)
print('ex2')
print(a[::3])
print('ex3')
a1 = np.array([np.sum(i) for i in a.reshape(33, 3)])
print(a1)
print('ex4')
oo = a1.reshape(11, 3)
print(a1.reshape(11, 3))
print('ex5')
o = a1.reshape(11, 3).T
print(a1.reshape(11, 3).T)
print('ex6')
b = np.array(np.arange(-9, 2).reshape(1, 11), float)
print(np.inner(a1.reshape(11, 3).T, b))
#print(np.matmul(a1.reshape(11, 3).T, b))
print('ex7')
srez = np.array(list(o[0, 1:12:4]) + list(o[2, 1:12:4])).reshape(2, 3)
print(srez)
print('ex8')
srez = np.array(list(oo[2, :]) + list(oo[5, :]) + list(oo[8, :])).reshape(3, 3)
print('ex9')
print(np.linalg.det(srez))